### ISSUE TITLE
Can't resolve 'contentlayer/generated'

### ISSUE THREAD

**Issue by aspsptyd** [ayoubkhial/ayoubkhial.com#15]
I need your help sir, 

![Screenshot 2024-06-20 at 22 12 13](https://github.com/ayoubkhial/ayoubkhial.com/assets/98740335/2f9c901d-5a79-419b-a61a-e572cac60c5a)

After clone the repo, i just run command `npm install` and `yarn install` for cover the package, but still error same

![Screenshot 2024-06-20 at 22 13 39](https://github.com/ayoubkhial/ayoubkhial.com/assets/98740335/937dc6b8-1bef-4402-997b-43cdc4e9308e)

**Comment by ayoubkhial** [comment]
Hello @aspsptyd ,

It appears that the **contentlayer** is no longer active due to funding issues. I recommend refraining from using it.

You can try resolving this issue by trying [this solution](https://github.com/contentlayerdev/contentlayer/issues/665).

**Comment by aspsptyd** [comment]
> Hello @aspsptyd ,
> 
> It appears that the **contentlayer** is no longer active due to funding issues. I recommend refraining from using it.
> 
> You can try resolving this issue by trying [this solution](https://github.com/contentlayerdev/contentlayer/issues/665).

Ok, i try it
